### ISSUE TITLE
Error got a string packages argument ("None"),

### ISSUE THREAD

**Issue by Charles1104** [fishtown-analytics/dbt-event-logging#42]
### Describe the bug

I am using DBT 0.20.1 with BigQuery. I have copied the macros "audit.sql" and "bigquery.sql" into my macro folder and I am using a prehook as follows:

`pre_hook='{{ logging.log_model_start_event() }}'`

And I then get the following error upon running "dbt run":

In adapter.dispatch, got a string packages argument ("None"), but packages should be None or a list.

### System information
**How did you add this package to your project:**
```
<packages.yml contents goes here>
```
I did not add the package directly but jsut took the macros file as I plan to amend the bahavior fo those macros. But I ran a pre-hook without chaging at all the macros and got the error mentionned above.

**Which database are you using dbt with?**
- [ ] Postgres
- [ ] Redshift
- [X ] BigQuery
- [ ] Snowflake
- [ ] Other (specify: ____________)

**The output of `dbt --version`:**
```
0.20.1
```

**Comment by jtcohen6** [comment]
@Charles1104 Rather than copy-pasting the macros from this package into your own root project, have you tried installing this package into your project, by defining it in `packages.yml` and running `dbt deps`?
```
# packages.yml
  - package: dbt-labs/logging
    version: 0.5.0
```
If you do that, you can still reference the macro from the project in your model hook. Everything should run successfully. This is the recommended way to use dbt packages, since you get all of the benefit, while introducing much less code surface area to maintain in your own project going forward.

Alternatively, you can copy-paste the macros from the package into your project, without actually installing the package. This type of "vendoring" is not generally recommended, but it can totally work. In this case, you'll just need to make a few small tweaks:
- Your model hook should call the macro as `'{{ log_model_start_event() }}'` rather than `'{{ logging.log_model_start_event() }}'`
- You need to replace the `macro_namespace` argument in the two calls to `adapter.dispatch`, [here](https://github.com/dbt-labs/dbt-event-logging/blob/7760cfc21d44265c5d865716ce54d946fca2ce60/macros/audit.sql#L31) and [here](https://github.com/dbt-labs/dbt-event-logging/blob/7760cfc21d44265c5d865716ce54d946fca2ce60/macros/audit.sql#L78). Instead of `'logging'`, you can either put the name of your own root project, or just leave that second argument empty. You can read [docs on `dispatch` functionality](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch) for the full details here. To make a long story short, because there is no installed package named `logging`, dbt doesn't know how to resolve macros that claim to be from that package's namespace.

**Comment by Charles1104** [comment]
@jtcohen6 : Installing the macros package works fine but we want to do quite some changes to those macros; hence why I started copy/pasting them.

Thank you for your explanations, this solved the issue and also helped the understanding of why it was failing. Much appreciated.

This issue can be closed.
