### ISSUE TITLE
INSERT Performance

### ISSUE THREAD

**Issue by kingfink** [fishtown-analytics/dbt-event-logging#8]
I don't have any quantitative evidence (yet) but anecdotally it seems `INSERT` operations for each model start/end may slow down our dbt runs. Also, from some research the AWS [docs](https://aws.amazon.com/blogs/big-data/top-10-performance-tuning-techniques-for-amazon-redshift/) state:

_These are leader node–based operations, and can create significant performance bottlenecks by maxing out the leader node network as data is distributed by the leader to the compute nodes._

Has anyone else run into this and do you have any advice on alternatives or remedies?

**Comment by drewbanin** [comment]
hey @kingfink - yeah, definitely, `insert`ing individual records is probably not a best-practice on analytical databases. I'm increasingly of the mind that using hooks for audit logging is a... suboptimal... decision, and I'd love to develop a better approach. I think whatever we come up with will probably look like a single batch load rather than a series of streamed inserts.

Will give this some thought and follow up here

**Comment by clrcrl** [comment]
We've now added a warning to the readme to let people know this (see #15)

**Comment by clrcrl** [comment]
Closing in favor of #16
